### ISSUE TITLE
Data Clustering Contest: Round 2

### ISSUE THREAD

**Issue by JohannesTK** [IlyaGusev/tgcontest#8]
Hi,

I hope you are in good health and congratulations on the winning the second and third place on Data Clustering Contest! Found your work through the well-written Medium post.

I was wondering to ask if the current repo has been updated with the round 2 results you have received in: https://entry1398-dcround2.usercontent.dev/ ? 🤗

Thank you,
Johannes

**Comment by IlyaGusev** [comment]
Hello!

Yes, this repo includes code and data for the second round of DC contest. We published most of our work right after the round finished.

However, for now, we do not provide new scripts for training models. We changed the training pipeline for categorization models: we utilized BERT-based classifiers to get automatic annotations for our lightweight fastText classifiers.

**Comment by JohannesTK** [comment]
Thanks for a quick response. Are you planning to release the training scripts as it would be helpful for pushing further research in the field?

**Comment by IlyaGusev** [comment]
Yes, we are planning to release the scripts. Though I don't believe these scripts can influence any research, the pseudo-labeling technique is not novel and we used it mainly because of performance limitations.

**Comment by IlyaGusev** [comment]
Training of categorization models: https://colab.research.google.com/drive/1fEmNPi41mnxLrc4hqamqi72xDCCH0Ima
